all:
  hosts:
    node1:
      ansible_host: 192.168.10.254
      ip: 192.168.10.254
      access_ip: 192.168.10.254
      etcd_member_name: etcd1
      ansible_user: vagrant
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
